### PR TITLE
GROOVY-7377: Interpolated variable followed by asterisk in slashy-str…

### PR DESCRIPTION
**Pull request by paulk-asert**
…ing causes compiler error

### CODE REVIEW

**Comment by paulk-asert** [comment]
Perhaps someone with some more Antlr 2 secret powers than me can help remove the warning:

    [ant:antlr] groovy.g: warning:lexical nondeterminism between rules ML_COMMENT and REGEXP_LITERAL upon
    [ant:antlr] groovy.g:     k==1:'/'
    [ant:antlr] groovy.g:     k==2:'*'
    [ant:antlr] groovy.g:     k==3:'\u0000'..'\ufffe'
    [ant:antlr] groovy.g:     k==4:'\u0000'..'\ufffe'

**Comment by PascalSchumacher** [comment]
Maybe @jespersm has a idea how to remove the warning?

**Comment by jespersm** [comment]
BTW: I tried, but I don't get why the warning occurs, the lookahead seems correctly specified.

**Comment by paulk-asert** [comment]
OK, thanks for checking. I ended up using a disambiguating semantic predicate and had to have it in it's own method so that the `atMultiCommentStart()` and `!atMultiCommentStart()` alternatives were recognized as distinct alternatives. Seems happy now but there might be a simpler way I couldn't fathom.

**Pull request merged**
