### PR TITLE
Groovy-7574: Ranges: Make Range members final. Also improve javadoc.

### PR DESCRIPTION
**Pull request by tkruse**
Else they can easily be changed in Groovy, which leads to undefined states

### CODE REVIEW

**Comment by tkruse** [comment]
Rebased, added commits forROOVY-7585, some refactorings, and tests

**Comment by paplorinc** [comment]
Interesting.

On a slightly different topic: how difficult would it be to support unbound ranges also, like in ```https://code.google.com/p/guava-libraries/wiki/RangesExplained```.

I don't know about the syntax, I guess `_..10` or `(..10)` or `<..10`.

Or ranges with non-integer step size, i.e. `0.1, 0.11, 0.11 ... 0.2` as `0.1..0.01..0.2` or at least to support integers in the ObjectRange's step setter :/

Let me know if you consider this off topic and will post it in the issues instead.

**Comment by tkruse** [comment]
non-integer ranges are already kind-of supported in Groovy. Ranges are defined by the "next()" method on the instances, which for 0.1..10 yields [0.1, 0.2, 0.3 ...]
Ranges can either be inspired by for-loops (having an increment step), or by mathematic intervals. Given Guava has ranges as you point out, I am not sure if Groovy should go out of its way to implement the same thing. 

Changing the grammar so that the parse can parse a larger variety of ranges should not be that difficult technically, but you may face resistance from language designers. Changing the code for the ranges an be a bit challenging, in particular since you must not break existing usages.

I am not sure if you are volunteering to work on this, or asking for this to be done. In any case I'd say the mailing lists are a good start to try to get support: http://www.groovy-lang.org/mailing-lists.html

**Comment by paplorinc** [comment]
> `0.1..10` yields `[0.1, 0.2, 0.3 ...]`

actually it yields `[0.1, 1.1, 2.1, 3.1, 4.1, 5.1, 6.1, 7.1, 8.1, 9.1]`, because it has a step size of `1`, so e.g. `(0.1..0.5).collect()` will yield `[0.1]`

> I am not sure if you are volunteering to work on this, or asking for this to be done.

Would gladly contribute, will ask the mailing list for opinions, thanks :)

**Comment by tkruse** [comment]
sorry for wrong info about floats.

**Comment by tkruse** [comment]
superceded by #141 and #142 and #143

**Pull request closed without merging**
