### PR TITLE
Upgrade to commons-cli 1.3: from OptionBuilder to Option.builder()

### PR DESCRIPTION
**Pull request by jacopoc**

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Looks good as far as I can tell. :+1:

**Comment by PascalSchumacher** [comment]
@paulk-asert What do you think? Is this ready to merge?

**Comment by jacopoc** [comment]
I guess it is not a question for me, but I am not sure, so just in case: in my opinion it should be merged but I am available to do any tests you think are important.

**Comment by paulk-asert** [comment]
Looks good from what I can see. Given that we don't have much "integration test" coverage for using our tools from the commandline, I just wanted to be a little cautious and manually double check all the changes. Also, I wondered whether the @SuppressWarnings("static-access") is related to the "synchronized" or not. If yes, we should be able to delete it. I might have time for those checks next week but happy for someone else to quickly cast their eyes over it and check that nothing changed and if that's the case, we should be good to go.

**Comment by paulk-asert** [comment]
Applied, thanks!

**Pull request closed without merging**
