### PR TITLE
GROOVY-7675 - Fix compilerCustomizationBuilder withConfig secureAst resolution

### PR DESCRIPTION
**Pull request by chiquitinxx**
I found this bug some moths ago, I forgot to create Jira. Maybe can happen in other config builders.

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Thanks for the pull request,

could you please also create a Jira issue?

Thanks!

**Comment by chiquitinxx** [comment]
Sure, I have created Jira: https://issues.apache.org/jira/browse/GROOVY-7675

**Comment by shils** [comment]
+1

**Comment by PascalSchumacher** [comment]
Thanks!

**Pull request closed without merging**
