### PR TITLE
GROOVY-7631 If p is a primitive value, p != null returns false when s…

### PR DESCRIPTION
**Pull request by shils**
…tatically compiled

### CODE REVIEW

**Comment by kgdev** [comment]
When will this be merged?

**Comment by graemerocher** [comment]
Pull request was opened at quarter to midnight on a Sunday European time, I suggest you give the Groovy guys a chance to wake up ;-)

**Comment by blackdrag** [comment]
looks ok to me

**Comment by PascalSchumacher** [comment]
@shils Thanks for the pull request :+1: !

@blackdrag Thanks for the review!

**Pull request closed without merging**
