### PR TITLE
fix after #172, Interpretermode tests also need to run all other tests

### PR DESCRIPTION
**Pull request by tkruse**
Sorry, I did not think that through. #172 is bad because it makes many tests from parent test class run without proper configuration.

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Test failed. Did you get a automatic notification for the failures?

**Comment by tkruse** [comment]
No, I get no mail notifications. Working on fixing...

**Comment by PascalSchumacher** [comment]
two fixed, two to go...

**Comment by PascalSchumacher** [comment]
Thanks! :)

**Pull request closed without merging**
