### PR TITLE
GROOVY-7618 Parameterless closure to SAM Type argument coercion cause…

### PR DESCRIPTION
**Pull request by shils**
…s NPE during instruction selection (STC)

### CODE REVIEW

**Comment by melix** [comment]
Hi @shils !

I am really impressed with your pull requests. That part of the codebase is not the easiest. Would you be interested in joining the team?

**Comment by shils** [comment]
Hi @melix ,

Thanks for reviewing my code. I'd love to join the team; what would the next steps be?

**Comment by PascalSchumacher** [comment]
@shils The existing committers have to vote. @melix I guess you will start the vote?

**Comment by PascalSchumacher** [comment]
I just started the vote. It will last for 72 hours. @shils Sorry for the delay.

**Comment by shils** [comment]
@PascalSchumacher That's alright, thanks for letting me know. There have been more important things to vote on recently anyway.

**Pull request closed without merging**
