### PR TITLE
Fixed UTF-16 BOM writing JavaDoc

### PR DESCRIPTION
**Pull request by keeganwitt**

### CODE REVIEW

**Comment by PascalSchumacher** [comment]
Hi Keegan,

thanks for the pull request. :)

It would be nice if you could squash the commits. Let know if this is to much bother, then I will do it for you.

Thanks!

**Comment by keeganwitt** [comment]
Sorry, bad SVN habits die hard.  Would you like these squashed as "removed JavaDoc erroneously stating UTF-16 BOM will be written" and "document UTF-16 BOM writing"?  Or just 1 commit?

**Comment by PascalSchumacher** [comment]
Thanks! Two commits are perfect. :+1:

**Comment by PascalSchumacher** [comment]
Thanks! :)

**Pull request closed without merging**
