### PR TITLE
GROOVY-7423: Access to Method parameter names at runtime.

### PR DESCRIPTION
**Pull request by nickgrealy**
@paulk-asert - New clean pull request (finally!)

### CODE REVIEW

**Comment by paulk-asert** [comment]
Looks great! Nice work!

**Comment by nickgrealy** [comment]
Cool cool cool. Just wanted to say thanks Paul, for the help and patience. What's the next step from here? Is there anything else I can do? (I'm conscious that time equals more rebasing...)

**Comment by paulk-asert** [comment]
Applied. Glad you persisted with your efforts. A neat feature to have!

**Comment by nickgrealy** [comment]
Awesome. :+1:

**Comment by nickgrealy** [comment]
**Note to self:** `git branch --all --contains` 7c735bfc1807df4e8fa44f02958c7a000634b6de

**Pull request closed without merging**
