### PR TITLE
Fix a sentence in `core-testing-guide.adoc`

### PR DESCRIPTION
**Pull request by EPadronU**

### CODE REVIEW

**Comment by keeganwitt** [comment]
While you're at it, could you add a comma before the "and Geb for..."?

**Comment by EPadronU** [comment]
Sure, I'll do it with pleasure. Do you think it would be convenient to drop this pull request and submit a new one with this changes plus the comma?

**Comment by keeganwitt** [comment]
You can if you want, but it's not like PRs make a snapshot of the content when they're opened, so what I usually do in these cases is
1. Commit the change
2. Squash it with your previous commit locally
3. Force push with `git push origin +master`

Overwriting the history like that is evil to do on a repo someone might fork.  But for cases like this, nobody's gonna fork a fork, so it's fine.

**Comment by EPadronU** [comment]
It's done. Cheers.

**Comment by keeganwitt** [comment]
Thanks!

**Comment by EPadronU** [comment]
My pleasure.

**Pull request closed without merging**
